import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ape1 from "./assets/ape3.webp";
import ape2 from "./assets/ape2.webp";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-[50px]  font-bold">Buy my physical NFTs</h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <Image src={ape1} width="332" height="232" className="" />
            <p>Hape NFT GoldGrill 30000$</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <Image src={ape2} width="332" height="232" />
            <p>Hape NFT Banana 100.000$</p>
          </a>
        </div>
      </main>
    </div>
  );
}
